# Offer Networks:  a model of decentralized exchange

We consider a simplified framework of decentralized barter exchange -- Offer Networks -- between independent and heterogeneous agents for demonstrating main properties of what we call **open-ended decentralized computing** -- a paradigm for researching and testing the possibility of computational emergence of open-ended intelligence [@weinbaum_weaver_open_2017],[@weinbaum_weaver_open-ended_2018] by performing computer simulations.

We first shortly introduce main concepts of open-ended decentralized computing and then show how they can be (at least partially) mapped to the Offer Networks architecture. Finally the results of preliminary experiments are presented and discussed.

## Open-ended decentralized computing

Open-ended intelligence is an abstraction of the process of human cognitive development, extended to general agents and systems. Three facets of it are the philosophical concept of individuation, sense-making and the individuation (via progressive determination) of general cognitive agents. Open-ended intelligence can be framed in terms of a decentralized, self-organising scalable network of interacting agents (or elements). A critical aspect of individuation of intelligence is disparity resolution and coordination among *a priori* independent and heterogeneous agents holding distinct value systems. Please see [@weinbaum_weaver_open_2017] for the introduction of the concept in the context of Artificial General Intelligence and [@weinbaum_weaver_open-ended_2018] for in-depth treatment of the metaphysical framework.

### Major aspects of the computational framework

Open-ended decentralized computing is a computational paradigm following and based on the Open-ended intelligence philosophy. Main aspects of it are:

* **Network of heterogenous agents**. First, since open-ended intelligence is framed in terms of decentralized network of interacting agents, it determines the usage of an Actor model of computation [@hewitt_universal_1973], [@agha_concurrent_1985], [@zenil_what_2013], [@hewitt_viewing_1976], which features communication medium where many independent and heterogeneous agents interact via message passing. Even though each individual actor in the framework can represent a deterministic computation (algorithm), Actor network in its general form is non-deterministic -- i.e. probabilistic and deterministic behaviours can be represented using it, but the general formalism itself is not constrained in any way by them.

* **Stigmergic coordintation**. Second, the possibility of progressive determination of emergent structures in the network (in terms of assemblages of actors) is implemented via the universal mechanism of stigmergic coordination [@heylighen_stigmergy_2016]. Stigmergy is a mechanism of indirect coordination between actions of otherwise independent actors via the shared medium or context where individual actions shape the medium and medium influences further individual actions in recursive way. Thus generalized concept of stigmergy is equivalent to the concept of progressive determination, which is the actual mechanism of individuation [@weinbaum_weaver_open_2017, veitas_living_2017]. In Open-ended decentralized computing the shared medium which allows for stigmergic coordination and progressive determination is implemented as a graph (concretely -- property graph [@robinson_graph_2015], [@rodriguez_graph_2010]) which can be read from and written to by each actor in a concurrent and asynchronous manner. Often used notion of stigmergy as indirect communication in colonies of eusocial insects (ants) via pheromone traces is actually but a special case of the concept.

* **Decentralization**. Third, since open-ended intelligence is not constrained by any pre-defined structures or goals, open-ended decentralized computing should follow this principle. This is implemented in practice by conceiving a framework which is not constrained by pre-defined structures and general goals, yet where they **can** emerge from the interaction among elements or indirectly influenced by limiting behavioural repertoire of agents participating in the network. This is implemented by strictly enforcing the principle of decentralization -- positing that there could exist no actor or agent a priori having complete and full knowledge of the network (i.e. underlying graph structure). Such agent in principle could emerge from indirect or direct coordination happening in the network, but it cannot obtain such "privileged" status before interaction begins (hence -- no *a priori*). The principle of decentralization, apart from conceptual importance, influences many software design and rather low level decisions on coding level -- e.g. prohibition of shared global data structures apart the network itself <sup>[1](#footnote1)</sup>.

<a name="footnote1">1</a>: Actually, even the usage of a global structure (a graph) for representing the network itself is determined by technical/pragmatic convenience rather than conceptual necessity.

### Directions of simulation modelling research

Open-ended decentralized computing is a research direction and a practically applicable paradigm. We have chosen to apply the simulation modelling research method for pursuing these research directions -- i.e. by (1) designing and implementing a software architecture based on aforementioned principles as well as having practical importance and (2) running computational experiments \end{inlinelist}. OfferNet(s) software architecture <sup>[2](#footnote2)</sup> is such a framework. Purposes of simulation modelling research reflect the double nature of software architecture -- as implementation of general computational framework of open-ended decentralized computing and a pragmatic application of it for solving well-definable problems. We first start with delineation of the former and then go to to describe the latter.

<a name="footnote2">2</a>: [https://github.com/singnet/offernet](https://github.com/singnet/offernet); development is supported by SingularityNET Foundation ([https://singularitynet.io/research-initiatives/](https://singularitynet.io/research-initiatives/)).

From the conceptual perspective we want to operationalize the principle progressive determination in a working software architecture. Such an architecture would demonstrate the practical aspects of open-ended intelligence philosophy and pave a way for the its application in practical contexts, including, but not limited to quest for the Artificial General Intelligence. In summary, the software architecture is meant for showing:

* The very possibility of implementing the mechanism of progressive determination in the computational medium;
* Identifying and demonstrating contexts where application of decentralized mechanism of progressive determination makes more sense from practical perspective than conventional centralized algorithms;
* Demonstrate bottom up emergence of higher order structures in the network having detectable, yet not *a priori* defined functionality in the context of the network; such structures would take form of ad-hoc assemblages of lower level actors, functionality of which is programmed directly depending on domain.

## Offer Networks

Offer Networks is a concept of an alternative economy where Agents (humans, AIs and or more/less simple programs and intelligences) find, negotiate and execute locally and globally beneficial series of not-only-monetary exchanges of tangible and/or intangible goods. It was first proposed by [@goertzel_beyond_2015] in the context of post-money economy and further developed by [@heylighen_offer_2017] in the context of Global Brain research.

For our purposes, Offer Networks is a practical context for implementing and testing the mechanism of progressive determination. Notwithstanding, it is also a research project on its own, aiming at conceiving, conceptualizing and proof-of-concept implementation of alternative economy for the age of decentralized and autonomous AI technologies.

### Research directions

#### Model specification

#### Research questions

### Experiment: comparison of decentralized and centralized search

## Discussion and further steps

