```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, error=FALSE, output=FALSE, source = FALSE)
Sys.setenv(ON_workdir = '/home/kabir/offernet/')
```

```{r git, engine='bash'}
export ON_codebase_version=$(git rev-parse --short HEAD)
echo $ON_codebase_version > ON_codebase_version.dat
```

```{r init}
fileName <- 'ON_codebase_version.dat'
ON_codebase_version <- readLines(file(fileName,open="r"))[1]
Sys.setenv(ON_codebase_version = ON_codebase_version)
Sys.setenv(ON_experimentId = "EXP08-11-12-58-3BvMSL")

#install.packages("jsonlite")
#install.packages("kableExtra")
#install.packages("ggplot2")
#install.packages('elastic')
library(elastic)
library(jsonlite)
library(knitr)
library(kableExtra)
```

# Experiment 2: pre-generated 'small world' graphs

## Experimental set up

<!--#### variables: -->
```{r get-experiment-info, results = 'asis', eval=TRUE}
library(elastic)
conn <-connect(es_port = 9200)
template <- '{ 
  "query": {
    "bool": {
      "must": [
        { "match_phrase": {
          "experimentId": "%s"
          }
        }
      ],
      "must_not": [
        { "exists": { "field": "simulationId" } }
      ]
    }
  }
}'
query <- sprintf(template, Sys.getenv('ON_experimentId'))
source=c('experimentId','agentNumbers','chainLengths','randomWorksNumberMultipliers','maxDistances','similaritySearchThresholds')


result <- Search(index="filebeat-*", source=source, body=query, asdf=TRUE, size=1000)$hits$hits
experiment.df <- result[,-c(1:4)]
vars=sapply(strsplit(colnames(experiment.df), split='.', fixed=TRUE), function(x) (x[2]))
colnames(experiment.df) <- vars
experiment.df <- experiment.df[c(3,1,2,4,5,6)]
experiment.df <- t(experiment.df)
colnames(experiment.df) <- c('Values')

# print Experiment data
kable(experiment.df) %>%
  kable_styling(bootstrap_options='condensed',full_width = FALSE, position = 'left') #%>%
    #column_spec(0:ncol(experiment.df),width="10em") 
    #add_header_above(c("labels"=5))


```

### Descriptive analysis of each simulation

```{r get-simulation-info, results = 'asis', eval=TRUE}
conn <-connect(es_port = 9200)
template <- '{ 
  "query": {
    "bool": {
      "must": [
        { "match_phrase": {
          "experimentId": "%s"
          }
        },
        { "match" :{
          "keyword": "simulationParameters"
        }},
        { "exists": { "field": "simulationId" } }
      ]
    }
  }
}'
query <- sprintf(template, Sys.getenv('ON_experimentId'))
source=c('simulationId','agentNumber','chainLength','ramdomWorksNumberMultiplier','maxDistance','similaritySearchThreshold')
result <- Search(index="filebeat-*", source=source, body=query, asdf=TRUE, size=1000)$hits$hits

simulations.df <- result[,-c(1:4)]
vars=sapply(strsplit(colnames(simulations.df), split='.', fixed=TRUE), function(x) (x[2]))
colnames(simulations.df) <- vars
simulations.df <- simulations.df[c(5,1,2,3,4)]
simulations.df <- simulations.df[order(simulations.df$agentNumber, simulations.df$chainLength, simulations.df$maxDistance, simulations.df$simulationId),]
# getting rid of the simulation data on which the experiment crashed -- gives error...
simulations.df <- simulations.df[which(simulations.df$simulationId != "SIM08-11-04-26-tNxY4J--DV"), ]
rownames(simulations.df) <- c()

simulationIds <- simulations.df$simulationId

  conn <-connect(es_port = 9200)
  template <- '{    "query": {
          "bool": {
            "must": [
              {"exists" : { "field" : "method" }},
              {"exists" : { "field" : "simulationId" }},
              { "bool": {
                "should": [
                    {"match_phrase": {
                      "method": "allEdgesByLabel"
                    }},
                    {"match_phrase": {
                      "method": "allVerticesByLabel"
                    }},
                    {"match_phrase": {
                      "method": "similarityEdgesByWeight"
                    }}
                ]
              }}
            ]
          }
      }}'
  query <- sprintf(template)
  source=c('simulationId','results', 'message', 'method','edgeLabel','vertexType','direction')
  result <- Search(index="filebeat-*", source=source, body=query, asdf=TRUE, size=10000)$hits$hits
  
  analysis.df <- result[,-c(1:4)]
  vars=sapply(strsplit(colnames(analysis.df), split='.', fixed=TRUE), function(x) (x[2]))
  colnames(analysis.df) <- vars

library(ggplot2)

for (simulationId in simulationIds) {
  cat(paste('### ',simulationId,'\n\n'))
  cat(paste('#### simulationParameters \n\n'))
  
  simulation.df <- simulations.df[which(simulations.df$simulationId == simulationId),][,-1]
  rownames(simulation.df) <-c()
  
  # output simulationParameters
  print(kable(simulation.df) %>%
    kable_styling(bootstrap_options='condensed',full_width = FALSE, position = 'left') %>%
      column_spec(1:1,width="20em") %>%
      column_spec(2:ncol(simulation.df),width="15em")
      #add_header_above(c("variables"))
  )
  
  simulationData <- analysis.df[which(analysis.df$simulationId == simulationId),]
  
  # output allEdgesByLabel
  edges.df <- data.frame(fromJSON(simulationData[which(simulationData$method == 'allEdgesByLabel'),]$results))
  edges.df$Total <- rowSums(edges.df)
  cat('#### allEdgesByLabel\n\n')
  print(kable(edges.df, format.args = list(decimal.mark = '.', big.mark = ",")) %>%
    kable_styling(bootstrap_options='condensed',full_width = FALSE, position = 'left') %>%
      column_spec(1:ncol(edges.df),width="5em") 
      #add_header_above(c("labels"=5))
  )
  
  # output allVerticesByType
  vertices.df <- data.frame(fromJSON(simulationData[which(simulationData$method == 'allVerticesByLabel'),]$results))
  vertices.df$Total <- rowSums(vertices.df)
  cat('#### allVerticesByType\n\n')
  print(kable(vertices.df, format.args = list(decimal.mark = '.', big.mark = ",")) %>%
    kable_styling(bootstrap_options='condensed',full_width = FALSE, position = 'left') %>%
      column_spec(1:ncol(vertices.df),width="5em") 
      #add_header_above(c("labels"=5))
  )
  
  # output similarityEdgesByWeight
  similarity <- data.frame(fromJSON(simulationData[which(simulationData$method == 'similarityEdgesByWeight'),]$results))
  wghts <- as.numeric(substring(unlist(names(similarity)),first = 2))
  frequencies <- as.numeric(similarity)
  similarity.df <- data.frame(weight=wghts,edges=frequencies)
  se <- ggplot(data=similarity.df, aes(x=weight, y=frequencies)) +
    geom_bar(stat="identity", fill="steelblue")+
    geom_text(aes(label=weight), vjust=1.6, color="white", size=3.5)+
    xlab("Weight")+
    ylab("Number of edges")+
    theme_minimal()+
    geom_line()
  
  cat('#### distribution of similarityEdgesByWeight\n\n')
  print(se)
  cat('\n\n')
  
  # plot degreeDistribution items-similarity
  conn <-connect(es_port = 9200)
  template <- '{
          "query": {
              "bool": {
                "must": [
                  {"exists" : { "field" : "method" }},
                  {"exists" : { "field" : "simulationId" }},
                  {"match_phrase": {
                    "simulationId": "%s"
                  }},
                  {"match_phrase": {
                    "method": "%s"
                  }},
                  {"match": {
                    "vertexType": "%s"
                  }},
                  {"match": {
                    "edgeLabel": "%s"
                  }},
                  { "match": {
                    "direction": "%s"
                  }}
                ]
              }
          }
      }'
  method <- 'degreeDistribution'
  vertexType <- 'item'
  edgeLabel <- 'similarity'
  direction <- 'out'
  query <- sprintf(template, simulationId, method, vertexType, edgeLabel, direction)
  source=c('simulationId','results', 'message', 'method','edgeLabel','vertexType','direction')
  result <- Search(index="filebeat-*", source=source, body=query, asdf=TRUE, size=100)$hits$hits
  
  data <- result[,-c(1:4)]
  vars=sapply(strsplit(colnames(data), split='.', fixed=TRUE), function(x) (x[2]))
  colnames(data) <- vars

  degrees <- fromJSON(data$results)
  dgr <- as.numeric(substring(unlist(names(degrees)),first = 2))
  frequencies <- as.numeric(degrees)
  degrees.df <- data.frame(degrees=dgr,frequencies=frequencies)
  
  dd_is <- ggplot(data=degrees.df, aes(x=dgr, y=frequencies)) +
    geom_bar(stat="identity", fill="white", color="black")+
    #geom_text(aes(label=dgr), vjust=1.6, color="black", size=3.5)+
    xlab("Degree")+
    ylab("Count")+
    theme_minimal()

  cat('#### Degree distribution of item->similarity->item edges\n\n')
  #print(kable(degrees.df))
  #cat('\n\n')
  print(dd_is)
  cat('\n\n')

  # plot degreeDistribution agent-knows
  conn <-connect(es_port = 9200)
  template <- '{
          "query": {
              "bool": {
                "must": [
                  {"exists" : { "field" : "method" }},
                  {"exists" : { "field" : "simulationId" }},
                  {"match_phrase": {
                    "simulationId": "%s"
                  }},
                  {"match_phrase": {
                    "method": "%s"
                  }},
                  {"match": {
                    "vertexType": "%s"
                  }},
                  {"match": {
                    "edgeLabel": "%s"
                  }},
                  { "match": {
                    "direction": "%s"
                  }}
                ]
              }
          }
      }'
  method <- 'degreeDistribution'
  vertexType <- 'agent'
  edgeLabel <- 'knows'
  direction <- 'both'
  query <- sprintf(template, simulationId, method, vertexType, edgeLabel, direction)
  source=c('simulationId','results', 'message', 'method','edgeLabel','vertexType','direction')
  result <- Search(index="filebeat-*", source=source, body=query, asdf=TRUE, size=100)$hits$hits
  
  data <- result[,-c(1:4)]
  vars=sapply(strsplit(colnames(data), split='.', fixed=TRUE), function(x) (x[2]))
  colnames(data) <- vars

  a_degrees <- fromJSON(data$results)
  dgr <- as.numeric(unlist(names(a_degrees)))
  frequencies <- as.numeric(a_degrees)
  a_degrees.df <- data.frame(degrees=dgr,frequencies=frequencies)
  
  dd_ak <- ggplot(data=a_degrees.df, aes(x=dgr, y=frequencies)) +
    geom_bar(stat="identity", fill="white", color="black")+
    #geom_text(aes(label=dgr), vjust=1.6, color="black", size=3.5)+
    xlab("Degree")+
    ylab("Count")+
    theme_classic()

  cat('#### Degree distribution of agent->knows->agent edges\n\n')
  #print(kable(a_degrees.df))
  #cat('\n\n')
  print(dd_ak)
  cat('\n\n')  
  
}

```


## Discussion and notes

Degree distributions over item -> similarity -> item links are clearly incorrect (the total number of similarity links in graphs are much higher than displayed in the graph -- need to test this).
