```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, error=FALSE, output=FALSE, source = FALSE)
Sys.setenv(ON_workdir = '/home/kabir/offernet/')
```

<!--#### variables: -->
```{r get-experiment-info, results = 'asis', eval=TRUE}
library(elastic)
library(jsonlite)
library(knitr)
library(kableExtra)
library(plyr)
library(stringi)

conn <-connect(es_port = 9200)
template <- '{
    "query": {
        "bool": {
          "must": [
            {"exists" : { "field" : "experimentId" }}
          ],
          "must_not": [
            {"exists" : { "field" : "simulationId"}}
          ]
        }
    },
    "sort": [
      {
        "@timestamp": {
          "order": "asc"
        }
      }
    ]
}'
query <- sprintf(template)
source=c('experimentId','@timestamp','agentNumbers','chainLengths','randomWorksNumberMultipliers','maxDistances','similaritySearchThresholds')
experiment.result <- Search(index="filebeat-*", source=source, body=query, asdf=TRUE, size=1000)$hits$hits
conn<-NULL
experiment.df <- experiment.result[,-c(1:5)]
vars=sapply(strsplit(colnames(experiment.df), split='.', fixed=TRUE), function(x) (x[2]))
colnames(experiment.df) <- vars
experiment.df <- experiment.df[c(4,3,1,2,5,6,7)]
# print Experiment data
cat(paste('## All experiments in database \n\n'))
kable(experiment.df) %>%
  kable_styling(bootstrap_options='condensed',full_width = FALSE, position = 'left') #%>%
    #column_spec(0:ncol(experiment.df),width="10em") 
    #add_header_above(c("labels"=5))

cat(paste('## Simulations of each experiment \n\n'))
experimentIds = experiment.df$experimentId
for (experimentId in experimentIds) {
  cat(paste('### ',experimentId,'\n\n'))
  conn <-connect(es_port = 9200)
  template <- '
        {
            "query": {
                "bool": {
                  "must": [
                    {"exists" : { "field" : "experimentId" }},
                    {"exists" : { "field" : "simulationId" }},
                    {"match_phrase": {
                      "experimentId": "%s"
                    }}
                  ],
                  "must_not": [
                    {"exists" : { "field" : "timeout_ms" }}
                  ]
                }
            },
            "sort": [
              {
                "@timestamp": {
                  "order": "asc"
                }
              }
            ]
        }  
  '

  query <- sprintf(template, experimentId)
  source=c('simulationId','randomWorksNumberMultiplier', 'similaritySearchThreshold','maxDistance','agentNumber','@timestamp','chainLength')
  exp.result <- Search(index="filebeat-*", source=source, body=query, asdf=TRUE, size=10000)$hits$hits
  conn<-NULL
  
  cat('\n\n')
  cat('\n\n')
  if (is.list(exp.result) & length(exp.result) != 0) {
    exp.df <- exp.result[,-c(1:5)]
    vars=sapply(strsplit(colnames(exp.df), split='.', fixed=TRUE), function(x) (x[2]))
    colnames(exp.df) <- vars
    exp.df <- exp.df[c(6,1,2,3,4,5,7)]
    template <- '
        {
            "query": {
                "bool": {
                  "must": [
                    {"exists" : { "field" : "experimentId" }},
                    {"exists" : { "field" : "simulationId" }},
                    {"exists" : { "field" : "timeout_ms" }},
                    {"match_phrase": {
                      "experimentId": "%s"
                    }}
                  ]
                }
            },
            "sort": [
              {
                "@timestamp": {
                  "order": "asc"
                }
              }
            ]
        }
    '
  query <- sprintf(template, experimentId)
  source=c('simulationId','timeout_ms')
  timeout.result <- Search(index="filebeat-*", body=query, source = source, asdf=TRUE, size=10000)$hits$hits
  conn<-NULL
  sims.df <- exp.df
  if (is.list(timeout.result) & length(timeout.result) != 0) {
    timeouts.df <- timeout.result[,-c(1:5)]
    vars=sapply(strsplit(colnames(timeouts.df), split='.', fixed=TRUE), function(x) (x[2]))
    colnames(timeouts.df) <- vars
    sims.df <- merge(x = exp.df, y = timeouts.df, by = "simulationId", all = TRUE)
  }

  ee <- kable(sims.df) %>%
    kable_styling(bootstrap_options='condensed',full_width = FALSE, position = 'left') #%>%
      #column_spec(0:ncol(experiment.df),width="10em") 
      #add_header_above(c("labels"=5))
  print(ee)

  cat(paste('## Running time of each simulation by method \n\n'))
  simulationIds = sims.df$simulationId
  
  for (simulationId in simulationIds) {1
      cat(paste('### ',simulationId, '\n\n'))
      cat(paste('#### simulationParameters \n\n'))
      
      params <- sims.df[which(sims.df$simulationId == simulationId),]
      params <- params[,-c(1,2)]
      rownames(params) <- c()
      simp <- kable(params) %>%
        kable_styling(bootstrap_options='condensed',full_width = FALSE, position = 'left') #%>%
      print(simp)
      
      for_sum.df <-data.frame()
      for_sum.df <- params
      for_sum.df$experimentId <- experimentId
      for_sum.df$simulationId <- simulationId

      conn <-connect(es_port = 9200)
      template <- '
            {
              "_source": false, 
              "query": {
                "match_phrase": { "simulationId" : "%s" }},
              "aggs": {
                "group_by_method": {
                  "terms": {
                    "field": "method.keyword"
                  },
                  "aggs": {
                    "group_by_method": {
                      "terms": {
                        "field": "method.keyword",
                        "order": {
                          "avg_wallTime_ms": "desc"
                        }
                      },
                      "aggs": {
                        "sum_wallTime_ms": {
                          "sum": {
                            "field": "wallTime_ms"
                          }
                        },
                        "avg_wallTime_ms": {
                          "avg": {
                            "field": "wallTime_ms"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }      
      '

      query <- sprintf(template, simulationId)
      sim.result <- Search(index="filebeat-*", body=query, asdf=TRUE, size=10000)
      sim.df <- sim.result$aggregations$group_by_method$buckets$group_by_method.buckets
      methods.df <- ldply(sim.df, data.frame)
      conn<-NULL
      func <- function(z) if (is.numeric(z)) sum(z) else ''
      sumrow <- as.data.frame(lapply(methods.df, func))      
      sumrow$avg_wallTime_ms.value <- ''
      sumrow$key <- "Total"
      for_sum.df$time_ms <- sumrow$sum_wallTime_ms
      for_sum.df$processes <- sumrow$doc_count
      last_row <- nrow(methods.df) +1
      m <- kable(rbind(methods.df,sumrow),format.args = list(decimal.mark = '.', big.mark = ",")) %>%
        kable_styling(bootstrap_options='condensed',full_width = FALSE, position = 'left') %>%
        row_spec(last_row, bold = TRUE)
          #column_spec(0:ncol(experiment.df),width="10em") 
          #add_header_above(c("labels"=5))
      print(m)
      
      keyword <- 'foundCycle'
      cat(paste('####  Found cycles \n\n'))
      
      conn <-connect(es_port = 9200)
      template <- '
            { 
              "query": {
                "bool": {
                  "must": [
                    { "match_phrase": {
                      "simulationId": "%s"
                      }
                    },
                    { "bool": {
                      "should": [
                        { "match": {
                          "keyword": "%s"
                        }}
                      ]
                    }}
                  ]
                }
              }
            }
  '

      query <- sprintf(template, simulationId, keyword)
      cycle.result <- Search(index="filebeat-*", body=query, asdf=TRUE, size=10000)
      cat(paste("Number of cycles found: ", cycle.result$hits$total),'\n\n')
      for_sum.df$foundCycles <- cycle.result$hits$total
      blockNo <- stri_rand_strings(1, 10, '[A-Z]')
      full_query <- sprintf("%s %s", '     GET /filebeat-*/_search', query)
      tooltip <- "To be used to extract graph from ElasticSearch and visualize via OfferNet visualization engine (given proper access permissions)"
      cat(paste('<button class="btn btn-primary" data-toggle="collapse" data-target="#',blockNo,'"> Show/Hide ',keyword,' query </button> \n <div id="',blockNo,'" class="collapse" >  \n',sep=''))
        cat(paste(full_query,'\n'))
        cat('\n</div>\n')
        
      keyword <- 'foundPath'
      cat(paste('####  Found paths \n\n'))
      
      conn <-connect(es_port = 9200)
      template <- '
            { 
              "query": {
                "bool": {
                  "must": [
                    { "match_phrase": {
                      "simulationId": "%s"
                      }
                    },
                    { "bool": {
                      "should": [
                        { "match": {
                          "keyword": "%s"
                        }}
                      ]
                    }}
                  ]
                }
              }
            }
  '

      query <- sprintf(template, simulationId, keyword)
      path.result <- Search(index="filebeat-*", body=query)
      cat(paste("Number of paths found: ", path.result$hits$total),'\n\n')
      for_sum.df$foundPaths <- path.result$hits$total
      blockNo <- stri_rand_strings(1, 10, '[A-Z]')
      full_query <- sprintf("%s %s", '     GET /filebeat-*/_search', query)
      cat(paste('<button class="btn btn-primary" data-toggle="collapse" data-target="#',blockNo,'"> Show/Hide ',keyword,' query </button> \n <div id="',blockNo,'" class="collapse" ">  \n',sep=''))
            cat(paste(full_query,'\n'))
        cat('\n</div>\n')        

      #cat(paste('### Sumary of simulation','\n\n'))
      
      #sum <- kable(for_sum.df,format.args = list(decimal.mark = '.', big.mark = ",")) %>%
      #  kable_styling(bootstrap_options='condensed',full_width = FALSE, position = 'left') #%>%
          #column_spec(0:ncol(experiment.df),width="10em") 
          #add_header_above(c("labels"=5))
      #print(sum)
    
    
    if (!exists('summary.df')) {
      summary.df <- for_sum.df
    } else{
      summary.df <- rbind.fill(summary.df, for_sum.df)
    }
    
  }
}


timeout.result <-NULL
experiment.result <-NULL
exp.result <-NULL

}

cat(paste('## Summary or running times \n\n'))
summary.df <- summary.df[c(7,8,1,2,3,4,5,6,9,10,11,12)]
summary <- kable(summary.df,format.args = list(decimal.mark = '.', big.mark = ",")) %>%
  kable_styling(bootstrap_options='condensed',full_width = FALSE, position = 'left') #%>%
    #column_spec(0:ncol(experiment.df),width="10em") 
    #add_header_above(c("labels"=5))
print(summary)
```