
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, error=FALSE, output=FALSE, source = FALSE)
Sys.setenv(ON_workdir = '/media/data/offernet/')
```

```{r git, engine='bash'}
cd $ON_workdir
export ON_codebase_version=$(git rev-parse --short HEAD)
cd analysis/elabnotebook-generate/tmp
echo $ON_codebase_version > ON_codebase_version.dat
```

```{r init}
fileName <- paste(Sys.getenv('ON_workdir'),'analysis/elabnotebook-generate/tmp/','ON_codebase_version.dat', sep="")
ON_codebase_version <- readLines(file(fileName,open="r"))[1]
Sys.setenv(ON_codebase_version = ON_codebase_version)
Sys.setenv(ON_experimentId = "EXP07-17-08-45-CP4PT2")
dataFilePath = paste(Sys.getenv('ON_workdir'),'analysis/elabnotebook-generate/tmp/',Sys.getenv('ON_experimentId'),'.json', sep="")
library(stringr)
Sys.setenv(ON_dataFilePath = dataFilePath)

#install.packages("jsonlite")
#install.packages("kableExtra")
#install.packages("ggplot2")
#install.packages('elastic')
library(elastic)
library(jsonlite)
library(knitr)
library(kableExtra)
```

Date: `r date()` <br/>
ExperimentId: `r Sys.getenv('ON_experimentId')` <br/>
Codebase version: [`r Sys.getenv('ON_codebase_version')`](`r paste('https://github.com/singnet/offernet/commit/',Sys.getenv('ON_codebase_version'),sep="")`) <br/>

## Experimental setup

<!--#### variables: -->
```{r get-experiment-info, results = 'asis', eval=FALSE}
conn <-connect(es_port = 9200)
template <- '{ 
  "query": {
    "bool": {
      "must": [
        { "match_phrase": {
          "experimentId": "%s"
          }
        }
      ],
      "must_not": [
        { "exists": { "field": "simulationId" } }
      ]
    }
  }
}'
query <- sprintf(template, Sys.getenv('ON_experimentId'))
result <- Search(index="filebeat-*", body=query)

vars <- c('experimentId', 'agentNumbers', 'maxDistances','chainLengths')
experiment <- result$hits$hits[[1]]$`_source`[vars]
experiment.df <- as.data.frame(experiment)

# print Experiment data
kable(experiment.df) %>%
  kable_styling(bootstrap_options='condensed',full_width = FALSE, position = 'left') %>%
    column_spec(1:ncol(experiment.df),width="10em") 
    #add_header_above(c("labels"=5))

```

#### simulations of the experiment:
```{r get-simulation-info, results = 'asis'}
conn <-connect(es_port = 9200)
template <- '{ 
  "query": {
    "bool": {
      "must": [
        { "match_phrase": {
          "experimentId": "%s"
          }
        },
        { "exists": { "field": "simulationId" } }
      ]
    }
  }
}'
query <- sprintf(template, Sys.getenv('ON_experimentId'))
result <- Search(index="filebeat-*", body=query)

vars <- c('agentNumber', 'maxDistance','chainLength', 'similaritySearchThreshold')
simulations_vars <- result$hits$hits[[1]]$`_source`[vars]
simulations_ids <- result$hits$hits[[1]]$`_source`[c('simulationId')]
simulations.df <- as.data.frame(t(t(simulations_vars)))
colnames(simulations.df) = simulations_ids


# print Experiment data
kable(simulations.df) %>%
  kable_styling(bootstrap_options='condensed',full_width = FALSE, position = 'left') %>%
    column_spec(1:1,width="20em") %>%
    column_spec(2:ncol(simulations.df),width="15em")
    #add_header_above(c("variables"))


```


### Network

```{r collect-network-statistics, engine='bash', eval=FALSE}
cd $ON_workdir
cd analysis/elabnotebook-generate/
groovy scripts/groovy/offernet_query_file.groovy allEdgesByLabel $ON_experimentId
groovy scripts/groovy/offernet_query_file.groovy allVerticesByLabel $ON_experimentId
groovy scripts/groovy/offernet_query_file.groovy similarityEdgesByWeight $ON_experimentId
groovy scripts/groovy/offernet_query_file.groovy degreeDistributionUndirected $ON_experimentId '{"labelValue":"agent","edgeLabel":"knows"}'
groovy scripts/groovy/offernet_query_file.groovy degreeDistributionDirected $ON_experimentId '{"labelValue":"item","edgeLabel":"similarity"}'
groovy scripts/groovy/offernet_query_file.groovy degreeDistributionUndirected $ON_experimentId '{"labelValue":"agent","edgeLabel":"owns"}'
groovy scripts/groovy/offernet_query_file.groovy degreeDistributionUndirected $ON_experimentId '{"labelValue":"work","edgeLabel":"demands"}'
groovy scripts/groovy/offernet_query_file.groovy degreeDistributionUndirected $ON_experimentId '{"labelValue":"work","edgeLabel":"offers"}'
```


```{r load-network-statistics, results="asis"}
#json_string <- readLines(file(dataFilePath,open='r'))[1]
json_data <- fromJSON(file(dataFilePath,open='r'), flatten=TRUE)
```

#### edges:
```{r allEdgesByLabel, results='asis'}
# print allEdgesByLabel
edges.df <- as.data.frame(json_data$allEdgesByLabel$data)
edges.df[,"Total"] = rowSums(edges.df)
#rownames(edges.df) <- c('Number of edges')
kable(edges.df, format.args = list(decimal.mark = '.', big.mark = ",")) %>%
  kable_styling(bootstrap_options='condensed',full_width = FALSE, position = 'left') %>%
    column_spec(1:ncol(edges.df),width="5em") 
    #add_header_above(c("labels"=5))
```

#### vertices:
```{r allVerticesByLabel, results='asis'}
# print table allVerticesByLabel
vertices.df <- as.data.frame(json_data$allVerticesByLabel$data)
vertices.df[,"Total"] = rowSums(vertices.df)
kable(vertices.df, format.args = list(decimal.mark = '.', big.mark = ",")) %>%
  kable_styling(bootstrap_options='condensed',full_width = FALSE, position = 'left') %>%
    column_spec(1:ncol(vertices.df),width="5em") 
    #add_header_above(c("labels"=5))
```

#### similarity edges by weight
```{r similarityEdgesByWeight, results='asis'}
# print plot similarityEdgesByWeight
similarity <-json_data$similarityEdgesByWeight$data
wghts <- as.numeric(unlist(names(similarity)))
frequencies <- as.numeric(similarity)
similarity.df <- data.frame(weight=wghts,edges=frequencies)

library(ggplot2)
se <- ggplot(data=similarity.df, aes(x=weight, y=frequencies)) +
  geom_bar(stat="identity", fill="steelblue")+
  geom_text(aes(label=weight), vjust=1.6, color="white", size=3.5)+
  xlab("Weght")+
  ylab("Number of edges")+
  theme_minimal()+
  geom_line()
se
```


#### Degree distribution of item->similarity->item edges
```{r degreeDistributonDirecteditemsimilarity, results='asis'}
# plot degreeDistribution items-similarity
degrees <- json_data$degreeDistributionDirecteditemsimilarity$data
dgr <- as.numeric(unlist(names(degrees)))
frequencies <- as.numeric(degrees)
degrees.df <- data.frame(degrees=dgr,frequencies=frequencies)

dd_is<-ggplot(degrees.df, aes(x=degrees)) +
  geom_histogram(binwidth=20, fill="white", color="black")+
  geom_vline(aes(xintercept=mean(dgr)), color="blue",
             linetype="dashed")+
  labs(x="Degree", y = "Count")+
  theme_classic()
dd_is
```

#### Degree distribution of agent->knows->agent edges
```{r degreeDistributionUndirectedagentknows, results='asis'}
# plot degreeDistribution agent-knows
degrees <- json_data$degreeDistributionUndirectedagentknows$data
dgr <- as.numeric(unlist(names(degrees)))
frequencies <- as.numeric(degrees)
degrees.df <- data.frame(degrees=dgr,frequencies=frequencies)

se <- ggplot(data=degrees.df, aes(x=degrees, y=frequencies)) +
  geom_bar(stat="identity")+
  geom_text(aes(label=frequencies), vjust=1.6, color="white", size=3.5)+
  scale_x_continuous(breaks=dgr)+
  xlab("Number of knows edges")+
  ylab("Number of agents")+
  theme_classic()
se

```

## Benchmarking and comparison



