# Link distribution

## Processes per agent

```{r elementary-processes, results='asis', echo=FALSE}
rm(list=ls())
fullPath <- Sys.getenv('R_fullPath')
setwd(fullPath)
agents.df <- read.table(file = "allChallengedAgents.dat",header=T,sep=',')

numberOfAgents = nrow(agents.df)
originalChallengesPerAgent = sum(agents.df$originalChallenges)/numberOfAgents
challengedPerAgent = sum(agents.df$challenged)/numberOfAgents
penalizedPerAgent = sum(agents.df$penalized)/numberOfAgents
benefittedPerAgent = sum(agents.df$benefitted)/numberOfAgents
bufferedPerAgent = sum(agents.df$buffered)/numberOfAgents
forgotPerAgent = sum(agents.df$forgot)/numberOfAgents
interpretedPerAgent = sum(agents.df$interpreted)/numberOfAgents
reinterpretedPerAgent = sum(agents.df$reinterpreted)/numberOfAgents
processedPerAgent = sum(agents.df$processed)/numberOfAgents

table = matrix(c(originalChallengesPerAgent,challengedPerAgent,interpretedPerAgent,bufferedPerAgent,processedPerAgent,penalizedPerAgent,benefittedPerAgent,forgotPerAgent,reinterpretedPerAgent),ncol=1,byrow=TRUE)
rownames(table) <- c('originalChallenges','challenged','interpreted','buffered','processed','penalized','benefitted','forgot','reinterpreted')
colnames(table) <- c('eventsPerAgent')
table <-as.table(table)

library(xtable);
print(xtable(table,align='lc',caption="average number of elementary events per agent"),type='html',include.rownames=TRUE, NA.string="n.a.");
```

## Distribution of original challenges

```{r original-challenges, echo=FALSE}
library(ggplot2)

cat(paste('The number of original challenges in the simulation: ',sum(agents.df$originalChallenges)))

ggplot(agents.df, aes(x=originalChallenges)) +
  geom_histogram(binwidth=.5) +
  xlab('Number of original challenges (from g-o-d) received') +
  ylab('Frequency (agents)')
```

## Distribution of all challenges


```{r all-challenges, echo=FALSE}
library(ggplot2)

cat(paste('Total number of all challenges in the simulation: ',sum(agents.df$challenged)))

ggplot(agents.df, aes(x=challenged)) +
  geom_histogram(binwidth=3) +
  xlab('Number of all challenges (from g-o-d and other agents) received') +
  ylab('Frequency (agents)')
```

## Distribution of processed challenges

```{r processed-challenges, echo=FALSE}
library(ggplot2)

cat(paste('Total number of all processed challenges in the simulation: ',sum(agents.df$processed)))

ggplot(agents.df, aes(x=processed)) +
  geom_histogram(binwidth=.9) +
  xlab('Number of processed challenges') +
  ylab('Frequency (agents)')
```

